# -*- coding: utf-8 -*-
"""openCVfaceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FzsFsKOFQBgrsPZf4W0d7pzlN7w70fuF
"""

!pip install opencv-python-headless

import cv2
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

filename = next(iter(uploaded))
image = cv2.imread(filename)

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image_rgb)
plt.axis('off')
plt.show()

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

for (x, y, w, h) in faces:
    cv2.rectangle(image_rgb, (x, y), (x+w, y+h), (255, 0, 0), 2)

plt.imshow(image_rgb)
plt.axis('off')
plt.show()